require('plugins')
require('options')
require('binds')

require('statusline-config')
require('lsp-config')
require('treesitter-config')
require('fzf-config')
require('netrw-config')
require('emmet-config')
